trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Build'

- script: |
    npm run test
  displayName: 'Run Tests'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure Web App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (b993e077-edb2-4d13-9503-74813054ce29)'
    appType: 'webAppLinux'
    WebAppName: 'Internship127'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'




